# Generated by Django 5.0.7 on 2024-10-12 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_articlecomment'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songartist',
            name='ArtistUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author'),
        ),
    ]
