# Generated by Django 5.0.7 on 2024-10-12 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_image_songartist_artist_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songartist',
            name='song',
            field=models.FileField(blank=True, null=True, upload_to='music/', validators=[django.core.validators.FileExtensionValidator(['M4A', 'FLAC', 'MP3', 'WAV', 'MP3'])]),
        ),
    ]
