# Generated by Django 5.0.7 on 2024-10-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_artist_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistname',
            name='name_of_artist',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
