# Generated by Django 5.0.7 on 2024-10-13 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_artist_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.artistname'),
        ),
        migrations.AlterField(
            model_name='songartist',
            name='artist_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.artistname'),
        ),
    ]
