# Generated by Django 5.0.7 on 2024-10-13 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_artist_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songartist',
            name='artist_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.artistname'),
        ),
    ]
