# Generated by Django 5.0.7 on 2024-10-14 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_songartist_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_song',
            field=models.FileField(blank=True, null=True, upload_to='music/', validators=[django.core.validators.FileExtensionValidator(['M4A', 'FLAC', 'MP3', 'WAV', 'MP3'])]),
        ),
        migrations.AddField(
            model_name='artist',
            name='song_genre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='song_title',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SongArtist',
        ),
    ]
