# Generated by Django 5.0.7 on 2024-10-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_artist_artist_profile_artist_artist_song_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='song_artist_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
