# Generated by Django 5.0.7 on 2024-10-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_artist_song_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='song_artist_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
