# Generated by Django 5.0.7 on 2024-10-14 05:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_artist_artist_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_artist_name_create', models.CharField(max_length=200, null=True, unique=True)),
                ('song_genre_create', models.CharField(max_length=200, null=True)),
                ('artist_song_create', models.FileField(blank=True, null=True, upload_to='music/', validators=[django.core.validators.FileExtensionValidator(['M4A', 'FLAC', 'MP3', 'WAV', 'MP3'])])),
                ('artist_genre_create', models.CharField(max_length=200, null=True)),
                ('artist_song_title_create', models.CharField(blank=True, null=True)),
                ('artist_image_create', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('artist_profile_create', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('posted_on_create', models.DateTimeField(auto_now_add=True)),
                ('artist_name_create', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_on_create'],
            },
        ),
    ]
