# Generated by Django 5.0.7 on 2024-11-03 04:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_createsong'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('sub_title', models.CharField(max_length=200, null=True, unique=True)),
                ('artist_song_create', models.FileField(blank=True, null=True, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(['M4A', 'FLAC', 'MP3', 'WAV', 'MP3'])])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('article_content', models.TextField(null=True)),
                ('dated_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-dated_on',),
            },
        ),
    ]
