# Generated by Django 5.0.7 on 2024-11-03 04:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sportsnews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SportsNews',
            new_name='SportsModel',
        ),
    ]
