# Generated by Django 5.0.7 on 2024-11-03 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_sportsnews_sportsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsmodel',
            name='artist_song_create',
            field=models.FileField(blank=True, null=True, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(['MOV', 'WMV', 'MP4', 'FLV', 'WEBM', 'AVI', 'MKV'])]),
        ),
    ]
