# Generated by Django 5.1.5 on 2025-01-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_sportsmodel_artist_song_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='song_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='createsong',
            name='artist_song_title_create',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
