# Generated by Django 5.1.5 on 2025-01-31 18:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_album_delete_createsong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_song',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='song_title',
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200, null=True)),
                ('song_file', models.FileField(blank=True, null=True, upload_to='music/', validators=[django.core.validators.FileExtensionValidator(['M4A', 'FLAC', 'MP3', 'WAV', 'MP3'])])),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='core.artist')),
            ],
        ),
    ]
