# Generated by Django 5.1.5 on 2025-02-01 22:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_song_artist_name_artist_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='core.album'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(blank=True, null=True, upload_to='music/', validators=[django.core.validators.FileExtensionValidator(['m4a', 'flac', 'mp3', 'wav'])]),
        ),
    ]
