# Generated by Django 5.1.5 on 2025-02-07 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif'])]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif'])]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif'])]),
        ),
    ]
