# Generated by Django 5.1.5 on 2025-02-08 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_album_cover_image_alter_artist_artist_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='song_covers/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'WebP', 'avif', 'jfif'])]),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'WebP', 'avif', 'jfif'])]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_cover/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'WebP', 'avif', 'jfif'])]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_profile',
            field=models.ImageField(blank=True, null=True, upload_to='artist_profile/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'WebP', 'avif', 'jfif'])]),
        ),
    ]
