# Generated by Django 5.1.5 on 2025-03-15 11:13

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_song_cover_image_alter_album_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsmodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'WebP', 'avif', 'jfif'])], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'WebP', 'avif', 'jfif'])], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'WebP', 'avif', 'jfif'])], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'WebP', 'avif', 'jfif'])], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
