# Generated by Django 5.1.5 on 2025-03-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_sportsmodel_image_alter_album_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(blank=True, null=True, upload_to='music'),
        ),
    ]
