# Generated by Django 5.1.5 on 2025-02-14 20:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_articlepostmodel_image_alter_postmodel_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_image/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'WebP', 'avif', 'jfif'])])),
                ('location', models.TextField(max_length=50)),
                ('item_status', models.CharField(choices=[('BRAND NEW', 'brand new'), ('FOREIGN USED', 'foreign used'), ('LOCAL USED', 'local used'), ('USED', 'used')], default='USED', max_length=12)),
                ('item_type', models.CharField(choices=[('AUTOMATIC', 'automatic'), ('MANUAL', 'manual')], default='AUTOMATIC', max_length=9)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
