# Generated by Django 5.1.5 on 2025-02-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('BRAND NEW', 'brand new'), ('FOREIGN USED', 'foreign used'), ('LOCAL USED', 'local used'), ('USED', 'used')], default=1, max_length=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('AUTOMATIC', 'automatic'), ('MANUAL', 'manual')], default=1, max_length=9),
        ),
    ]
