# Generated by Django 5.1.5 on 2025-02-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_item_options_item_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(blank=True, choices=[('AUTOMATIC', 'automatic'), ('MANUAL', 'manual')], default=1, max_length=9),
        ),
    ]
