# Generated by Django 5.1.5 on 2025-02-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='enable',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
