# Generated by Django 5.1.5 on 2025-03-15 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_library'),
    ]

    operations = [
        migrations.DeleteModel(
            name='library',
        ),
    ]
