# Generated by Django 5.1.5 on 2025-03-15 11:13

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_delete_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepostmodel',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'WebP', 'avif', 'jfif'])], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'WebP', 'avif', 'jfif'])], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'WebP', 'avif', 'jfif'])], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'WebP', 'avif', 'jfif'])], verbose_name='image'),
        ),
    ]
