# Generated by Django 5.0.7 on 2024-09-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profilemodel_first_name_profilemodel_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='about',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='talk_about',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
