# Generated by Django 5.0.7 on 2024-09-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profilemodel_about_profilemodel_talk_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
