# Generated by Django 5.0.7 on 2024-09-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profilemodel_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='talk_about',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='talks_about',
            field=models.CharField(default='anything', max_length=255, null=True),
        ),
    ]
