# Generated by Django 5.0.7 on 2024-09-30 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_person_profilemodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='last_name',
        ),
    ]
