# Generated by Django 5.0.7 on 2024-10-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_first_name_profilemodel_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='email',
        ),
    ]
