# Generated by Django 5.1.5 on 2025-01-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_profilemodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
