# Generated by Django 5.1.5 on 2025-02-02 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profilemodel_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jfif'])]),
        ),
    ]
